[package]
name = "cmt_tester"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

irony_cmt = {path = "../irony_cmt"}
cement = {path = "../../cement"}
num-bigint = "0.4.4"
